// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nflsgpgndroxfyssftnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mbHNncGduZHJveGZ5c3NmdG5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjA2NDksImV4cCI6MjA2ODgzNjY0OX0.xsdZtzDudeZdw03pYJ0TowfEogN2PfzGpdLtFE7D9vs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});